import Head from "next/head";
import Image from "next/image";
import { Loading } from "./Loading";
import { ToastContainer } from "react-toastify";
import { Header } from "./Header";

import "react-toastify/dist/ReactToastify.css";

interface LayoutProps {
  children: React.ReactNode;
}

export function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Chá de Bebe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/baby-elephant.png" />
      </Head>
      <Header />
      <main
        id="main-content"
        className="flex flex-col w-full min-h-[calc(100vh-112px)] relative scrollbar-thin scrollbar-track-zinc-50 scrollbar-thumb-zinc-900"
      >
        {children}
        <div className="absolute z-0 w-full h-full flex items-center justify-center top-0 left-0">
          <Image
            priority
            alt="bebe elefante"
            src="/baby-elephant.png"
            width={0}
            height={0}
            sizes="100vw"
            className="w-[500px] h-[500px]"
          />
        </div>
      </main>
      <Loading />
      <ToastContainer
        position="bottom-left"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />
    </>
  );
}
