import { ToastContainer } from "react-toastify";
import { Header } from "./Header";

import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { Loading } from "./Loading";

interface LayoutProps {
  children: React.ReactNode;
}

export function Layout({ children }: LayoutProps) {
  const router = useRouter();

  const isHome = router.pathname === "/";

  return (
    <>
      <Head>
        <title>Chá de Bebe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/baby-elephant.png" />
      </Head>
      <Header />
      <main
        id="main-content"
        className="flex flex-col w-full min-h-[calc(100vh-112px)] relative"
      >
        {children}
        <div className="absolute z-0 w-full h-full flex items-center justify-center top-0 left-0">
          <Image
            alt="bebe elefante"
            className={`${
              !isHome && "opacity-60 "
            } transition-opacity duration-500 z-0`}
            src="/baby-elephant.png"
            width={500}
            height={500}
          />
        </div>
      </main>
      <Loading />
      <ToastContainer
        position="bottom-left"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />
    </>
  );
}
