export const myItems = [
  "01 escovinha de cabelos e 01 pente + 01 Pomada(Bepantol ou Hipoglós)",
  "01 kit de manicure + 01 pacote de lenço umedecido",
  "01 aspirador nasal + 01 pacote de Fralda P",
  "01 álcool 70% e 08 pacotes de algodão + 01 Pomada (Bepantol ou Hipoglós)",
  "01 massageador de gengiva e 01 creme dental",
  "01 Pomada (Bepantol ou Hipoglós) + 01 pacote de lenço umedecido",
  "01 Pomada (Bepantol ou Hipoglós) + 01 pacote de lenço umedecido",
  "01 pacote de fralda RN + 01 pacote de lenço umedecido",
  "01 pacote de fralda RN + 01 pacote de lenço umedecido",
  "01 pacote de fralda P + 01 pacote de lenço umedecido",
  "01 pacote de fralda P + 01 pacote de lenço umedecido",
  "01 pacote de fralda P + 01 pacote de lenço umedecido",
  "01 pacote de fralda P + 01 pacote de lenço umedecido",
  "01 almofada de amamentação + 01 pacote de lenço umedecido",
  "01 bomba de tirar leite + 01 pacote de lenço umedecido",
  "01 caixa de absorvente para seios + 01 pacote de lenço umedecido",
  "01 caixa de absorvente para seios + 01 pacote de lenço umedecido",
  "01 caixa de absorvente para seios + 01 pacote de lenço umedecido",
  "01 caixa de absorvente para seios + 01 pacote de lenço umedecido",
  "01 mordedor + 01 pomada (Bepantol ou Hipoglós)",
  "01 mordedor + 01 pomada (Bepantol ou Hipoglós)",
  "01 kit de maternidade (saquinhos para separar as roupas do bebê) + 1 pacote de lenço umedecido",
  "01 banheira com trocador",
  "01 saboneteira + 01 pacote de fralda P",
  "01 cesto de roupas + 01 pacote de fralda P",
  "01 termômetro de banho + 01 pacote de fralda P",
  "01 toalha com capuz + 1 shampoo (Johnson ou Granado)",
  "01 toalha com capuz + 1 sabonete líquido (Johnson ou Granado)",
  "01 toalha com capuz + 1 sabonete líquido (Johnson ou Granado)",
  "01 toalha com capuz + 1 shampoo (Johnson ou Granado)",
  "01 toalha fralda + 1 óleo Johnson",
  "01 toalha fralda + brinquedos para banho",
  "01 toalha fralda + 01 pacote de fralda P",
  "01 toalha fralda + 01 pacote de fralda P",
  "01 chupeta ortodôntica fase 1 (0 a 6 meses - lilo, kuka, avent ou mam) + 01 porta chupeta",
  "01 chupeta ortodôntica fase 1 (0 a 6 meses - lilo, kuka, avent ou mam) + 01 porta chupeta",
  "01 prendedor de chupetas + 01 chuquinha (lilo, kuka, avent ou mam) e um bico reserva para chuquinha",
  "01 prendedor de chupetas + 01 mamadeira fase 1 (0 a 6 meses - lilo, kuka, avent ou mam) e um bico reserva para mamadeira",
  "01 prendedor de chupetas + 01 mamadeira fase 2 (mais de 6 meses - lilo, kuka, avent ou mam) e um bico reserva para mamadeira",
  "01 mamadeira fase 2 (mais de 6 meses - lilo, kuka, avent ou mam) e um bico reserva para mamadeira + 01 porta leite em pó",
  "01 mamadeira fase 2 (mais de 6 meses - lilo, kuka, avent ou mam) + 01 conjunto de coador e funil",
  "01 pinça higiênica (para pegar mamadeiras e chupetas esterilizados) + 01 kit de escova para mamadeiras",
  "01 garrafinha térmica + 01 porta leite em pó",
  "01 Leiteira antiaderente",
  "01 Panelinha antiaderente + 01 termômetro clínico",
  "01 Kit com 3 paninhos de boca + 01 pacote de fralda M",
  "01 Kit com 3 paninhos de boca + 01 pacote de fralda M",
  "01 Kit com 3 paninhos de boca + 01 pacote de fralda M",
  "01 kit com 3 paninhos de boca + 01 pacote de fralda M",
  "01 fralda de ombro + 01 pacote de fralda M",
  "01 fralda de ombro + 01 pacote de fralda M",
  "01 fralda de ombro + 01 pacote de fralda M",
  "01 fralda de ombro + 01 pacote de fralda M",
  "01 fralda de ombro + 01 pacote de fralda M",
  "01 body de manga longa RN + 01 pacote de fralda G",
  "01 body de manga longa RN + 01 pacote de fralda G",
  "01 body de manga longa P + 01 pacote de fralda G",
  "01 body de manga longa P + 01 pacote de fralda G",
  "01 body de manga longa P + 01 pacote de fralda G",
  "01 body de manga longa M + 01 pacote de fralda G",
  "01 body de manga longa M + 01 pacote de fralda G",
  "01 body de manga longa M + 01 pacote de fralda G",
  "01 body de manga longa G + 01 pacote de fralda G",
  "01 body de manga longa G + 01 pacote de fralda G",
  "01 body de manga longa G + 01 pomada (Bepantol ou Hipoglós)",
  "01 body de manga curta RN + 01 pomada (Bepantol ou Hipoglós)",
  "01 body de manga curta RN + 01 pomada (Bepantol ou Hipoglós)",
  "01 body de manga curta P + 01 pacote de lenço umedecido",
  "01 body de manga curta P + 01 pacote de lenço umedecido",
  "01 body de manga curta P + 01 pacote de lenço umedecido",
  "01 body de manga curta M + 01 pacote de lenço umedecido",
  "01 body de manga curta M + 01 pacote de lenço umedecido",
  "01 body de manga curta M + 01 pacote de lenço umedecido",
  "01 body de manga curta G + 01 pacote de lenço umedecido",
  "01 body de manga curta G + 01 pacote de lenço umedecido",
  "01 body de manga curta G + 01 pacote de lenço umedecido",
  "01 calça (com pé/sem pé) + 01 Talco (Johnson ou Granado)",
  "01 calça (com pé/sem pé) + 01 trocador portátil",
  "01 calça (com pé/sem pé) + kit alimentação (talher e pratinho)",
  "01 calça (com pé/sem pé) + 2 pares de luvas",
  "01 macacão + 01 par de meia",
  "01 macacão + 01 par de meia",
  "01 macacão + 01 par de meia",
  "01 macacão + 01 par de meia",
  "01 sapatinho de tecido (lã, linho, crochê) + 02 gorrinhos",
  "01 sapatinho de tecido (lã, linho, crochê) + 01 casaquinho (lã, linho, crochê)",
  "01 casaquinho (lã, linho, crochê) + 01 manta para passeio",
  "01 manta para passeio + 01 babador",
  "01 babador + 01 pacote de lenço umedecido",
  "01 babador + 01 pacote de lenço umedecido",
  "01 babador + 01 pacote de lenço umedecido",
  "01 capa para colchonete do carrinho + 01 capa para bebê conforto",
  "01 capa para colchonete do carrinho + 01 capa para bebê conforto",
  "01 capa para colchonete do carrinho + 01 capa para bebê conforto",
  "01 capa de chuva para carrinho + 01 mosquiteiro para carrinho",
  "01 móbile para carrinho",
  "01 capa protetora de sol para bebê conforto",
  "01 bolsinha térmica",
  "01 canguru ergonômico",
  "01 protetor para colchão",
  "01 jogo de lençol para berço + 01 fronha avulsa",
  "01 jogo de lençol para berço + 01 fronha avulsa",
  "01 jogo de lençol para berço + 01 fronha avulsa",
  "01 cobertor ou edredom + 01 mosquiteiro",
  "01 cobertor ou edredom + 01 mosquiteiro",
  "01 manta para enrolar (cueiro)",
  "01 manta para enrolar (cueiro)",
  "01 móbile",
  "01 pacote de fralda M + 01 pomada (Bepantol ou Hipoglós)",
  "01 Kit de cabides + 01 pacote de lenço umedecido",
];
